name: Vendo arquivo compartilhado entre Jobs
on:
  push:
    branches:
      - main

jobs:
    job_1:
        runs-on: ubuntu-latest
        steps:
            - name: Confere versao do ubuntu 
              run: cat /etc/os-release
            
            - name: Exibir uma mensagem
              run: echo "Estou fazendo o curso de GitHub Actions da Linuxtips" > ${{github.workspace}}/mensagem.txt

            - uses: actions/upload-artifact@v4
              with:
                name: strigus-upload
                path: ${{github.workspace}}/mensagem.txt


         
    job_2: 
        runs-on: ubuntu-latest
        needs: job_1
        steps:
          - uses: actions/download-artifact@v4
            with:
              name: strigus-upload--
              path: strigus

          - name: Ver o conteudo da pasta strigus
            run: ls -lhat && ls ./strigus/

          - name: Acessa arquivo mensagem
            run: mv strigus/mensagem.txt . && rm -rf ./strigus

          - name: Ver o conteudo do diretorio
            run: ls -lhat 

          - name: Acessa arquivo mensagem
            run: cat mensagem.txt 

          



