name: Meu segundo workflow

on:
  push:
    branches:
    - main

jobs:
  giropops:
    steps:
    - name: Confere versao do ubuntu
      run: cat /etc/os-release
    - name: Printa uma mensagem na tela
      run: echo "Meu segundo workflow"
