name: Validacao de ambiente
on:
  workflow_dispatch:
    inputs:
      env:
        required: true
        type: choice
        options:
          - dev
          - stage
          - prod

jobs: 
  job-call-workflow:
    uses: ./.github/workflows/2-build-e-testes.yml
    with:
      ambiente: ${{inputs.env}}


          
