name: criando nossa trigger status
on:
  status

jobs:
  if_error_or_failure:
    runs-on: ubuntu-latest
    if: >-
      github.event.state == 'error' ||
      github.event.state == 'failure'
    steps:
      - env:
          DESCRIPTION: ${{github.event.description}}
        run: |
           The status is error or failed: $DESCRIPTION
  if_success:
    runs-on: ubuntu-latest
    if: >-
      github.event.state == 'success'
    steps:
      - env:
          DESCRIPTION: ${{github.event.description}}
        run: |
          echo the status ir success: $DESCRIPTION
